name: iOS CI (today-s-sound)

on:
  pull_request

jobs:
  lint-build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install tools (SwiftFormat/SwiftLint)
        run: |
          brew update
          brew install swiftformat swiftlint

      - name: Format check (no edits)
        run: swiftformat . --lint

      - name: Lint (strict)
        run: swiftlint --strict

      - name: Build & Test (Simulator)
        run: |
          xcodebuild \
            -project today-s-sound.xcodeproj \
            -scheme today-s-sound \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -sdk iphonesimulator \
            -configuration Debug \
            clean build
